spring:
  application:
    name: ms-productos
  config:
    import: "optional:configserver:http://localhost:8888"
  profiles:
    active: dev

  cloud:
    config:
      username: root
      password: s3cr3t
